# Site settings
title: on software development // gmaslowski.com
email: gregmaslowski@gmail.com
description: on software development
url:  # the base hostname & protocol for your site
twitter_username: gmaslowski
github_username:  gmaslowski

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  projects:
    output: true
    permalink: /projects/:path/


