# Site settings
title: on software development // gmaslowski.com
email: gregmaslowski@gmail.com
description: on software development
url:  http://gmaslowski.com
twitter_username: gmaslowski
github_username:  gmaslowski

gems: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  projects:
    output: true
    permalink: /projects/:path/

