# Site
title: gmaslowski.com
description: on software development
url: https://gmaslowski.com
# url: http://localhost:4000
logo: images/profile.jpg
locale: en_US

# Left Block Images
background:
  homepage: images/akka-1.jpg                           # this image will be shown on homepage's left block
  post-list: images/akka-1.jpg             # this image will be shown on post list page
  default-post: images/akka-1.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-131478104-1

# Social Links
#email:             email
#google.plus:        username
twitter:            gregmaslowski
#facebook:           username
github:             gmaslowski
stackoverflow:     2392469/gmaslowski
linkedin:          gmaslowski
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
